<?php
/**
 * File: User.php
 * Email: becksonq@gmail.com
 * Date: 12.12.2017
 * Time: 22:37
 */

namespace frontend\models\user;

use dektrium\user\models\User as BaseUser;


class User extends BaseUser
{
    public function register()
    {
        echo 'user - action register'; die;
        //return parent::register(); // TODO: Change the autogenerated stub
    }
}