<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%images}}".
 *
 * @property integer $id
 * @property string $ad_id
 * @property string $name
 * @property string $image
 * @property string $filename
 * @property string $size
 * @property string $path
 */
class Images extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%images}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ad_id', 'name'], 'required'],
            [['ad_id', 'name', 'image', 'filename', 'path'], 'string', 'max' => 255],
            [['size'],'integer'],
            [['filename'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ad_id' => 'Ad ID',
            'name' => 'Name',
            'image' => 'Image',
            'filename' => 'Filename',
            'size' => 'Size',
            'path' => 'Path',
        ];
    }

    public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub

    }
}
