<?php

namespace frontend\models;

use Yii;
use board\entities\Adverts;

/**
 * This is the model class for table "{{%images}}".
 *
 * @property integer $id
 * @property string $ad_id
 * @property string $name
 * @property string $image
 * @property string $filename
 * @property string $size
 * @property string $path
 */
class Images extends \yii\db\ActiveRecord
{
    public $images;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%images}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [ [ 'sid' ], 'required' ],
            [ [ 'filename', 'path' ], 'string', 'max' => 255 ],
            [ [ 'sid' ], 'string', 'max' => 32 ],
            [ [ 'ad_id', 'marker', 'main_image', 'size' ], 'integer' ],
            [ [ 'filename' ], 'unique' ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'         => 'ID',
            'ad_id'      => 'Ad ID',
            'marker'     => 'Marker',
            'sid'        => 'Sid',
            'main_image' => 'Main image',
            'filename'   => 'Filename',
            'size'       => 'Size',
            'path'       => 'Path',
        ];
    }

    public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub

    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdverts()
    {
        return $this->hasOne( Adverts::className(), [ 'id' => 'ad_id' ] );
    }
}
