<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%images}}".
 *
 * @property integer $id
 * @property string $ad_id
 * @property string $name
 * @property string $image
 * @property string $filename
 * @property string $size
 * @property string $path
 */
class Images extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%images}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [ [ 'sid' ], 'required' ],
            [ [ 'image', 'filename', 'path' ], 'string', 'max' => 255 ],
            [ [ 'sid' ], 'string', 'max' => 32 ],
            [ [ 'ad_id', 'marker', 'size' ], 'integer' ],
            [ [ 'filename' ], 'unique' ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'       => 'ID',
            'ad_id'    => 'Ad ID',
            'sid'      => 'Sid',
            'marker'   => 'Marker',
            'image'    => 'Image',
            'filename' => 'Filename',
            'size'     => 'Size',
            'path'     => 'Path',
        ];
    }

    public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub

    }
}
